dist: trusty
sudo: required

notifications:
  email: true

services:
  - docker

language: c

install:
  - git clone https://github.com/sancus-pma/sancus-main.git
  - cd sancus-main/docker && make build SANCUS_SECURITY=$SECURITY 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker images
  - docker tag sancus-devel $DOCKER_USERNAME/sancus-devel-$SECURITY
  - docker push $DOCKER_USERNAME/sancus-devel-$SECURITY

script:
  - docker run --name sancus-ci-run -d -t $DOCKER_USERNAME/sancus-devel-$SECURITY
  - >
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; 
    then 
    docker exec sancus-ci-run /bin/sh -c 
    "cd /sancus/sancus-examples &&
    ln -s /sancus/sancus-examples /travis_sancus-example &&
    git checkout $TRAVIS_BRANCH"; 
    else 
    docker exec sancus-ci-run /bin/sh -c	
    "git clone https://github.com/${TRAVIS_PULL_REQUEST_SLUG} /sancus-examples-pr &&
    cd /sancus-examples-pr && ln -s /sancus-examples-pr /travis_sancus-example &&
    git checkout $TRAVIS_PULL_REQUEST_SHA";
    fi
  - docker exec sancus-ci-run /bin/sh -c "cd /travis_sancus-example && make SANCUS_SECURITY=$SECURITY ARCHIVE_MODE=$ARCHIVE_MODE TRAVIS=1 $TARGET.sim"
  - docker ps -a

jobs:
  include:
    - stage: "Build and push Sancus simulator Docker images"
      env: SECURITY=64
      script: skip
    - env: SECURITY=128
      script: skip
    - stage: "Run Sancus example applications"
      env: TARGET=hello-world   SECURITY=64
      install: skip
    - env: TARGET=hello-world   SECURITY=128
      install: skip
    - env: TARGET=hello-library SECURITY=64
      install: skip
    - env: TARGET=hello-library SECURITY=64 ARCHIVE_MODE=thin
      install: skip
    - env: TARGET=sensor-reader SECURITY=64
      install: skip
    - env: TARGET=arithmetic    SECURITY=64
      install: skip
    - env: TARGET=fileio        SECURITY=64
      install: skip
    - env: TARGET=timer         SECURITY=64
      install: skip
    - env: TARGET=violation     SECURITY=64
      install: skip
    - env: TARGET=sancus-step   SECURITY=64
      install: skip
    - env: TARGET=dma           SECURITY=64
      install: skip
